import PopBet
g = PopBet.Game()
g.newPlayer(100)
g.newPlayer(200,45)
g.getAllPlayers()
g.setCurrentPlayer(100)
g.setLevel(PopBet.level.MEDIUM)
g.setPoints(True)
g.getPoints(100)
g.setCurrentPlayer(200)
g.setLevel(PopBet.level.MEDIUM)
g.setPoints(False)
g.getPoints(200)
g.getCard()
g.getPointsAllPlayers()
